'use strict';
const assert=require('node:assert/strict');
const bundle=require('./cpu-audit-summary-bundle');
const evidence=require('./cpu-audit-review-evidence');
const trend=require('./cpu-audit-review-trend');
const clear={kind:'cpu-audit-public-advisory',readOnly:true,requiresReview:false,changed:false,issueTrend:'unchanged',warnings:[]};
const flagged={...clear,requiresReview:true,changed:true,issueTrend:'increased',warnings:['Data issue count increased']};
const a=evidence.create(bundle.build([clear]));
const b=evidence.create(bundle.build([flagged]));
const s=trend.summarize([a,b,a]);
assert.equal(s.count,3);
assert.equal(s.reviewCount,1);
assert.equal(s.reviewStateChanges,2);
assert.equal(s.transitions.length,2);
assert.ok(Object.isFrozen(s)&&Object.isFrozen(s.transitions));
assert.equal(trend.summarize([]).count,0);
assert.throws(()=>trend.summarize(Array(21).fill(a)),TypeError);
assert.throws(()=>trend.summarize([a,{...b,reasons:['forged']}]),TypeError);
assert.match(trend.describe([a,b]),/Human-review snapshots: 1/);
console.log('Aggregate advisory review trend tests passed');
