'use strict';
const assert=require('node:assert/strict');
const summary=require('./cpu-audit-summary-bundle');
const original=require('./cpu-audit-review-evidence');
const bundles=require('./cpu-audit-review-trend-bundle');
const evidence=require('./cpu-audit-review-trend-evidence');
const timeline=require('./cpu-audit-review-trend-evidence-timeline');
const clear={kind:'cpu-audit-public-advisory',readOnly:true,requiresReview:false,changed:false,issueTrend:'unchanged',warnings:[]};
const flagged={...clear,requiresReview:true,changed:true,issueTrend:'increased',warnings:['Data issue count increased']};
const a=original.create(summary.build([clear]));
const b=original.create(summary.build([flagged]));
const normal=evidence.create(bundles.build([a]));
const warning=evidence.create(bundles.build([a,b]));
const result=timeline.summarize([normal,warning,normal]);
assert.equal(result.count,3);
assert.equal(result.reviewCount,1);
assert.equal(result.reviewStateChanges,2);
assert.equal(result.transitions.length,2);
assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.transitions));
assert.equal(timeline.summarize([]).reviewCount,0);
assert.throws(()=>timeline.summarize(Array(21).fill(normal)),TypeError);
assert.throws(()=>timeline.summarize([normal,{...warning,reasons:['forged']}]),TypeError);
assert.match(timeline.describe([normal,warning]),/Human-review snapshots: 1/);
console.log('Aggregate review trend evidence timeline tests passed');
