'use strict';
const assert=require('node:assert/strict');
const summary=require('./cpu-audit-summary-bundle');
const evidence=require('./cpu-audit-review-evidence');
const bundles=require('./cpu-audit-review-trend-bundle');
const gate=require('./cpu-audit-review-trend-gate');
const clear={kind:'cpu-audit-public-advisory',readOnly:true,requiresReview:false,changed:false,issueTrend:'unchanged',warnings:[]};
const flagged={...clear,requiresReview:true,changed:true,issueTrend:'increased',warnings:['Data issue count increased']};
const a=evidence.create(summary.build([clear]));
const b=evidence.create(summary.build([flagged]));
assert.equal(gate.assess(bundles.build([])).requiresHumanReview,true);
assert.equal(gate.assess(bundles.build([a])).requiresHumanReview,false);
const result=gate.assess(bundles.build([a,b]));
assert.equal(result.requiresHumanReview,true);
assert.equal(result.reasons.length,2);
assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.reasons));
assert.throws(()=>gate.assess({...bundles.build([a]),text:'forged'}),TypeError);
assert.match(gate.describe(bundles.build([a,b])),/human review needed/);
console.log('Aggregate review trend gate tests passed');
