'use strict';
const assert=require('node:assert/strict');
const api=require('./cpu-audit-review-evidence-timeline-gate');
const bundles=require('./cpu-audit-review-evidence-timeline-bundle');
const empty=bundles.build([]);
const missing=api.assess(empty);
assert.equal(missing.requiresHumanReview,true);
assert.deepEqual(missing.reasons,['No review evidence timeline snapshots available']);
assert.equal(missing.snapshotCount,0);
assert.ok(Object.isFrozen(missing)&&Object.isFrozen(missing.reasons));
const clear={kind:'cpu-audit-public-review-evidence-timeline-summary',readOnly:true,count:2,reviewCount:0,reviewStateChanges:0,transitionCount:1};
const presentation=require('./cpu-audit-review-evidence-timeline-presentation');
const cleanBundle={kind:'cpu-audit-public-review-evidence-timeline-bundle',readOnly:true,summary:clear,text:presentation.describe(clear)};
assert.equal(api.assess(cleanBundle).requiresHumanReview,false);
const flagged={...clear,reviewCount:1,reviewStateChanges:1};
const flaggedBundle={...cleanBundle,summary:flagged,text:presentation.describe(flagged)};
assert.deepEqual(api.assess(flaggedBundle).reasons,['Human review flags occurred in evidence timeline','Human review requirement changed in evidence timeline']);
assert.throws(()=>api.assess({...flaggedBundle,text:'forged'}),TypeError);
assert.match(api.describe(flaggedBundle),/human review needed/);
console.log('Aggregate review evidence timeline gate tests passed');
