'use strict';
const assert=require('node:assert/strict');
const summary=require('./cpu-audit-summary-bundle');
const original=require('./cpu-audit-review-evidence');
const bundles=require('./cpu-audit-review-trend-bundle');
const evidence=require('./cpu-audit-review-trend-evidence');
const api=require('./cpu-audit-review-evidence-timeline-export');
const clear={kind:'cpu-audit-public-advisory',readOnly:true,requiresReview:false,changed:false,issueTrend:'unchanged',warnings:[]};
const flagged={...clear,requiresReview:true,changed:true,issueTrend:'increased',warnings:['Data issue count increased']};
const a=original.create(summary.build([clear]));
const b=original.create(summary.build([flagged]));
const normal=evidence.create(bundles.build([a]));
const warning=evidence.create(bundles.build([a,b]));
const v=api.create([normal,warning,normal]);
assert.deepEqual(api.parse(api.stringify(v)),v);
assert.equal(v.count,3);
assert.equal(v.reviewCount,1);
assert.equal(v.reviewStateChanges,2);
assert.equal(v.transitionCount,2);
assert.ok(Object.isFrozen(v));
assert.deepEqual(api.parse(api.stringify(api.create([]))),api.create([]));
assert.throws(()=>api.validate({...v,reviewCount:4}),TypeError);
assert.throws(()=>api.validate({...v,transitionCount:1}),TypeError);
assert.throws(()=>api.parse('x'.repeat(513)),TypeError);
console.log('Aggregate review evidence timeline export tests passed');
