'use strict';
const assert=require('node:assert/strict');
const records=require('./cpu-audit-review-evidence-timeline-record');
const presentation=require('./cpu-audit-review-evidence-timeline-presentation');
const timeline=require('./cpu-audit-review-evidence-record-timeline');
const clean={kind:'cpu-audit-public-review-evidence-timeline-summary',readOnly:true,count:2,reviewCount:0,reviewStateChanges:0,transitionCount:1};
const flagged={...clean,reviewCount:1,reviewStateChanges:1};
function record(summary){return records.create({kind:'cpu-audit-public-review-evidence-timeline-bundle',readOnly:true,summary,text:presentation.describe(summary)});}
const a=record(clean),b=record(flagged);
const result=timeline.summarize([a,b,a]);
assert.equal(result.count,3);
assert.equal(result.reviewCount,1);
assert.equal(result.reviewStateChanges,2);
assert.equal(result.transitions.length,2);
assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.transitions));
assert.equal(timeline.summarize([]).reviewCount,0);
assert.throws(()=>timeline.summarize(Array(21).fill(a)),TypeError);
assert.throws(()=>timeline.summarize([a,{...b,reasons:['forged']}]),TypeError);
assert.match(timeline.describe([a,b]),/Human-review snapshots: 1/);
console.log('Aggregate review evidence record timeline tests passed');
