'use strict';
const assert=require('node:assert/strict');
const summary=require('./cpu-audit-summary-bundle');
const original=require('./cpu-audit-review-evidence');
const bundles=require('./cpu-audit-review-trend-bundle');
const evidence=require('./cpu-audit-review-trend-evidence');
const diff=require('./cpu-audit-review-trend-evidence-diff');
const clear={kind:'cpu-audit-public-advisory',readOnly:true,requiresReview:false,changed:false,issueTrend:'unchanged',warnings:[]};
const flagged={...clear,requiresReview:true,changed:true,issueTrend:'increased',warnings:['Data issue count increased']};
const a=original.create(summary.build([clear]));
const b=original.create(summary.build([flagged]));
const before=evidence.create(bundles.build([a]));
const after=evidence.create(bundles.build([a,b]));
const change=diff.compare(before,after);
assert.equal(change.reviewChanged,true);
assert.equal(change.snapshotCountDelta,1);
assert.equal(change.reviewCountDelta,1);
assert.equal(change.reviewStateChangesDelta,1);
assert.deepEqual(change.addedReasons,['Review flags occurred in trend','Review requirement changed in trend']);
assert.deepEqual(change.resolvedReasons,[]);
assert.ok(Object.isFrozen(change)&&Object.isFrozen(change.addedReasons));
assert.equal(diff.compare(after,after).reviewChanged,false);
assert.throws(()=>diff.compare(before,{...after,reasons:['forged']}),TypeError);
assert.match(diff.describe(before,after),/Review flags delta: 1/);
console.log('Aggregate review trend evidence comparison tests passed');
