'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {exportCPUReviewFeed}=require('./hlm-cpu-review-export');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const json=exportCPUReviewFeed(state,'PIT',{selections,reviewPageSize:2});
assert.strictEqual(json.exportedRows,2);
assert.strictEqual(JSON.parse(json.content).rows.length,2);
assert.strictEqual(json.executionEnabled,false);
const csv=exportCPUReviewFeed(state,'PIT',{selections,reviewExportFormat:'csv'});
assert.strictEqual(csv.mimeType,'text/csv');
assert.strictEqual(csv.content.split('\n').length,4);
assert.strictEqual(csv.content.startsWith('id,title,subtitle,section,actionKind,executionEnabled'),true);
assert.throws(()=>exportCPUReviewFeed(state,'PIT',{reviewExportFormat:'xml'}),RangeError);
assert.strictEqual(Object.isFrozen(json),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 391-395 CPU review export tests passed.');
