'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {assessCPUReviewReadiness}=require('./hlm-cpu-review-readiness');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const result=assessCPUReviewReadiness(state,'PIT',{selections});
assert.strictEqual(result.receipt.valid,true);
assert.strictEqual(result.receipt.readyForHumanReview,true);
assert.strictEqual(result.receipt.readyForExecution,false);
assert.strictEqual(result.receipt.blockers.length,2);
assert.strictEqual(result.receipt.pending.length,1);
assert.deepStrictEqual(result.receipt.issues,['blocked-items-require-review']);
assert.strictEqual(result.receipt.executionEnabled,false);
assert.strictEqual(Object.isFrozen(result.receipt),true);
const empty=assessCPUReviewReadiness(state,'PIT');
assert.strictEqual(empty.receipt.valid,true);
assert.strictEqual(empty.receipt.readyForHumanReview,false);
assert.strictEqual(empty.receipt.readyForExecution,false);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 331-335 CPU review readiness tests passed.');
