'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const authorization=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization});
const advancementVerification=verifyNextGameCalendarAdvancement({plan,authorization,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advancementVerification});
const verification=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
assert.strictEqual(verification.kind,'next-game-gamestate-calendar-candidate-verification');assert.strictEqual(verification.version,1);
assert.strictEqual(verification.verified,true);assert.strictEqual(verification.dateOnlyChangeVerified,true);assert.strictEqual(verification.targetGameMatched,true);
assert.strictEqual(verification.targetGame,candidate.targetGame);assert.strictEqual(verification.targetGame.type,'game');
assert.strictEqual(verification.sourceState,state);assert.strictEqual(verification.candidate,candidate);assert.strictEqual(verification.state,candidate.state);
assert.strictEqual(verification.calendarCandidateVerification.verified,true);assert.strictEqual(verification.state.meta.currentDate,'2027-03-05');
assert.strictEqual(state.meta.currentDate,'2027-03-03');assert.strictEqual(Object.isFrozen(verification),true);
assert.throws(()=>verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate:{...candidate,targetGame:{...candidate.targetGame}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_CANDIDATE_VERIFICATION_FAILED');
const tampered=JSON.parse(JSON.stringify(candidate.state));tampered.meta.controlledTeamId='NYR';
assert.throws(()=>verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate:{...candidate,state:tampered,calendarCandidate:{...candidate.calendarCandidate,state:tampered}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_CANDIDATE_VERIFICATION_FAILED');
assert.throws(()=>verifyNextGameGameStateCalendarCandidate({sourceState:createGameStateEnvelope({meta:{currentDate:'2027-03-04'}}),candidate}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_CANDIDATE_VERIFICATION_FAILED');
assert.throws(()=>verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate:{...candidate,targetGame:{...candidate.targetGame,type:'news'}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_CANDIDATE_VERIFICATION_FAILED');
console.log('Next-game GameState calendar candidate verification tests passed.');
