'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {buildCPUReviewWorkflow}=require('./hlm-cpu-review-workflow');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const full=buildCPUReviewWorkflow(state,'PIT',{selections});
assert.deepStrictEqual(full.counts,{total:3,blocked:2,awaitingExecution:1,filtered:3});
assert.strictEqual(full.snapshot.rows.length,3);
assert.strictEqual(full.snapshot.rows[0].status,'blocked');
assert.strictEqual(full.snapshot.rows[0].executionEnabled,false);
assert.strictEqual(full.diagnostics.requiresHumanReview,true);
assert.strictEqual(full.snapshot.executedCount,0);
const page=buildCPUReviewWorkflow(state,'PIT',{selections,statusFilter:'blocked',pageSize:1,page:2});
assert.strictEqual(page.counts.filtered,2);
assert.strictEqual(page.snapshot.totalPages,2);
assert.strictEqual(page.snapshot.rows.length,1);
assert.strictEqual(page.snapshot.rows[0].status,'blocked');
assert.strictEqual(page.snapshot.rows[0].order,2);
const empty=buildCPUReviewWorkflow(state,'PIT');
assert.strictEqual(empty.diagnostics.empty,true);
assert.strictEqual(empty.snapshot.totalPages,0);
assert.throws(()=>buildCPUReviewWorkflow(state,'PIT',{statusFilter:'unknown'}),RangeError);
assert.throws(()=>buildCPUReviewWorkflow(state,'PIT',{pageSize:0}),RangeError);
assert.throws(()=>buildCPUReviewWorkflow(state,'PIT',{page:0}),RangeError);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 316-320 CPU review workflow tests passed.');
