'use strict';
const assert=require('assert');const {createMasterCalendar}=require('./hlm-master-calendar');const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');const {createCalendarEventIndex}=require('./hlm-calendar-event');const {createGameStateEnvelope}=require('./hlm-game-state');const {createSimulationStopRules}=require('./hlm-simulation-stop-rules');
const {SIMULATION_COMMANDS,createSimulationCommand,planSimulationCommand}=require('./hlm-simulation-command');const {authorizeSimulationCommand,executeSimulationCommandCalendar,verifySimulationCommandCalendar}=require('./hlm-simulation-command-execution');
const {createSimulationGameStateCandidate,verifySimulationGameStateCandidate,authorizeSimulationGameStateActivation,activateSimulationGameState,verifySimulationGameStateActivation}=require('./hlm-simulation-gamestate-integration');
function fixture(mode){const calendar=createMasterCalendar({currentDate:'2027-04-17'}),timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-04-01',endDate:'2027-04-30'},{phaseId:'playoffs',startDate:'2027-05-01',endDate:'2027-05-31'}]}),eventIndex=createCalendarEventIndex({events:[{id:'news',type:'news',date:'2027-04-18'},{id:'game-1',type:'game',date:'2027-04-20',important:true},{id:'award',type:'award',date:'2027-05-31'}]}),stopRules=createSimulationStopRules({behaviors:{important:'notify'}}),state=createGameStateEnvelope({meta:{currentDate:'2027-04-17'},players:[{id:'p1'}]});
 const plan=planSimulationCommand({calendar,timeline,eventIndex,stopRules,command:createSimulationCommand({command:mode})}),authorization=authorizeSimulationCommand({plan,approved:true}),execution=executeSimulationCommandCalendar({calendar,plan,authorization}),verification=verifySimulationCommandCalendar({execution});return {state,verification};}
for(const mode of SIMULATION_COMMANDS){const f=fixture(mode),candidate=createSimulationGameStateCandidate(f),candidateVerification=verifySimulationGameStateCandidate({sourceState:f.state,candidate}),authorization=authorizeSimulationGameStateActivation({verification:candidateVerification,approved:true}),activation=activateSimulationGameState({verification:candidateVerification,authorization}),verification=verifySimulationGameStateActivation({activation});
 assert.strictEqual(verification.verified,true);assert.strictEqual(verification.mode,mode);assert.strictEqual(activation.state.meta.currentDate,f.verification.toDate);assert.strictEqual(f.state.meta.currentDate,'2027-04-17');assert.strictEqual(activation.state.universe.players[0].id,'p1');assert.notStrictEqual(activation.state,f.state);}
{const f=fixture('week'),candidate=createSimulationGameStateCandidate(f),v=verifySimulationGameStateCandidate({sourceState:f.state,candidate});assert.throws(()=>authorizeSimulationGameStateActivation({verification:v,approved:false}),e=>e.code==='SIMULATION_GAMESTATE_ACTIVATION_NOT_AUTHORIZED');}
console.log('Unified simulation GameState integration tests passed.');