'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createDailyTickPlan}=require('./hlm-daily-tick-plan');
const {createDailyTickAuthorization}=require('./hlm-daily-tick-authorization');
const {executeIsolatedDailyTickCalendar}=require('./hlm-daily-tick-calendar-execution');
const {verifyDailyTickCalendarExecution}=require('./hlm-daily-tick-calendar-verification');
const {createDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate');
const {verifyDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate-verification');
const {createDailyTickGameStateCalendarActivationAuthorization}=require('./hlm-daily-tick-gamestate-activation-authorization');
const {activateDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-activation');
const {verifyIsolatedDailyTickGameStateCalendarActivation}=require('./hlm-daily-tick-gamestate-activation-verification');

const sourceState=createGameStateEnvelope({meta:{currentDate:'2027-04-17',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:sourceState.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2026-10-06',endDate:'2027-04-17'},{phaseId:'playoffs',startDate:'2027-04-18',endDate:'2027-06-20'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-04-18',important:true}]});
const plan=createDailyTickPlan({calendar,timeline,eventIndex});
const tickAuthorization=createDailyTickAuthorization({plan,approved:true});
const calendarResult=executeIsolatedDailyTickCalendar({calendar,plan,authorization:tickAuthorization});
const calendarVerification=verifyDailyTickCalendarExecution({sourceCalendar:calendar,plan,authorization:tickAuthorization,result:calendarResult});
const candidate=createDailyTickGameStateCalendarCandidate({state:sourceState,verification:calendarVerification});
const candidateVerification=verifyDailyTickGameStateCalendarCandidate({sourceState,candidate});
const authorization=createDailyTickGameStateCalendarActivationAuthorization({verification:candidateVerification,approved:true});
const activation=activateDailyTickGameStateCalendarCandidate({verification:candidateVerification,authorization});
const verification=verifyIsolatedDailyTickGameStateCalendarActivation({activation});
assert.strictEqual(verification.kind,'isolated-daily-tick-gamestate-calendar-activation-verification');assert.strictEqual(verification.version,1);
assert.strictEqual(verification.verified,true);assert.strictEqual(verification.exactlyOneDayVerified,true);
assert.strictEqual(verification.candidateIdentityPreserved,true);assert.strictEqual(verification.authorizationLineageVerified,true);
assert.strictEqual(verification.eventsUnprocessed,true);assert.strictEqual(verification.gameSimulationPerformed,false);
assert.strictEqual(verification.universeSystemsProcessed,false);assert.strictEqual(verification.persistencePerformed,false);
assert.strictEqual(verification.fromDate,'2027-04-17');assert.strictEqual(verification.toDate,'2027-04-18');assert.strictEqual(verification.days,1);
assert.strictEqual(verification.activation,activation);assert.strictEqual(verification.state,candidate.state);
assert.strictEqual(sourceState.meta.currentDate,'2027-04-17');assert.strictEqual(verification.state.meta.currentDate,'2027-04-18');
assert.deepStrictEqual(verification.state.universe.players,sourceState.universe.players);assert.strictEqual(Object.isFrozen(verification),true);
assert.throws(()=>verifyIsolatedDailyTickGameStateCalendarActivation({activation:{...activation,persistencePerformed:true}}),e=>e.code==='DAILY_TICK_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
assert.throws(()=>verifyIsolatedDailyTickGameStateCalendarActivation({activation:{...activation,authorization:{...authorization,verification:{...candidateVerification}}}}),e=>e.code==='DAILY_TICK_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
assert.throws(()=>verifyIsolatedDailyTickGameStateCalendarActivation({activation:{...activation,state:createGameStateEnvelope({meta:{currentDate:'2027-04-18'}})}}),e=>e.code==='DAILY_TICK_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
console.log('Isolated daily tick GameState activation verification tests passed.');
