'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUReviewReport}=require('./hlm-cpu-review-reporting');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const result=createCPUReviewReport(state,'PIT',{selections});
assert.strictEqual(result.total,3);
assert.strictEqual(result.groups.find(x=>x.status==='blocked').count,2);
assert.strictEqual(result.groups.find(x=>x.status==='awaiting-execution').count,1);
assert.strictEqual(result.actions.reduce((sum,x)=>sum+x.count,0),3);
assert.strictEqual(result.checklist.length,3);
assert.ok(result.checklist.every(x=>x.reviewCompleted===false&&x.executionAuthorized===false));
assert.strictEqual(result.nextReviewId,result.checklist[0].id);
assert.strictEqual(result.executedCount,0);
assert.strictEqual(createCPUReviewReport(state,'PIT').total,0);
assert.strictEqual(JSON.stringify(state),before);
assert.deepStrictEqual(JSON.parse(JSON.stringify(result)).groups,result.groups);
console.log('Phase 9 Missions 321-325 CPU review reporting tests passed.');
