'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createDailyTickPlan}=require('./hlm-daily-tick-plan');
const {createDailyTickAuthorization}=require('./hlm-daily-tick-authorization');
const {executeIsolatedDailyTickCalendar}=require('./hlm-daily-tick-calendar-execution');
const {verifyDailyTickCalendarExecution}=require('./hlm-daily-tick-calendar-verification');
const {createDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate');
const {verifyDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate-verification');
const {createDailyTickGameStateCalendarActivationAuthorization}=require('./hlm-daily-tick-gamestate-activation-authorization');
const {activateDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-activation');
const {verifyIsolatedDailyTickGameStateCalendarActivation}=require('./hlm-daily-tick-gamestate-activation-verification');

const sourceState=createGameStateEnvelope({meta:{currentDate:'2027-04-17',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:sourceState.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2026-10-06',endDate:'2027-04-17'},{phaseId:'playoffs',startDate:'2027-04-18',endDate:'2027-06-20'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-04-18',important:true}]});
const plan=createDailyTickPlan({calendar,timeline,eventIndex});
const tickAuthorization=createDailyTickAuthorization({plan,approved:true});
const calendarResult=executeIsolatedDailyTickCalendar({calendar,plan,authorization:tickAuthorization});
const calendarVerification=verifyDailyTickCalendarExecution({sourceCalendar:calendar,plan,authorization:tickAuthorization,result:calendarResult});
const candidate=createDailyTickGameStateCalendarCandidate({state:sourceState,verification:calendarVerification});
const candidateVerification=verifyDailyTickGameStateCalendarCandidate({sourceState,candidate});
const authorization=createDailyTickGameStateCalendarActivationAuthorization({verification:candidateVerification,approved:true});
const activation=activateDailyTickGameStateCalendarCandidate({verification:candidateVerification,authorization});
const activationVerification=verifyIsolatedDailyTickGameStateCalendarActivation({activation});
const {createDailyTickPersistenceReadiness}=require('./hlm-daily-tick-persistence-readiness');
const readiness=createDailyTickPersistenceReadiness({verification:activationVerification});
const {createDailyTickPersistenceAuthorization,assertDailyTickPersistenceAuthorized}=require('./hlm-daily-tick-persistence-authorization');
const persistenceAuthorization=createDailyTickPersistenceAuthorization({readiness,approved:true});
const {createDailyTickPersistenceExecutionPackage}=require('./hlm-daily-tick-persistence-execution-package');
const executionPackage=createDailyTickPersistenceExecutionPackage({readiness,authorization:persistenceAuthorization});
const {createDailyTickPersistenceExecutionAuthorization,assertDailyTickPersistenceExecutionAuthorized}=require('./hlm-daily-tick-persistence-execution-authorization');
const executionAuthorization=createDailyTickPersistenceExecutionAuthorization({package:executionPackage,approved:true});
assert.strictEqual(executionAuthorization.kind,'daily-tick-persistence-execution-authorization');assert.strictEqual(executionAuthorization.version,1);
assert.strictEqual(executionAuthorization.approved,true);assert.strictEqual(executionAuthorization.executed,false);assert.strictEqual(executionAuthorization.days,1);
assert.strictEqual(executionAuthorization.fromDate,'2027-04-17');assert.strictEqual(executionAuthorization.toDate,'2027-04-18');
assert.strictEqual(executionAuthorization.package,executionPackage);assert.strictEqual(executionAuthorization.candidateState,executionPackage.candidateState);
assert.strictEqual(assertDailyTickPersistenceExecutionAuthorized(executionPackage,executionAuthorization),true);assert.strictEqual(Object.isFrozen(executionAuthorization),true);
assert.strictEqual(sourceState.meta.currentDate,'2027-04-17');assert.strictEqual(executionAuthorization.candidateState.meta.currentDate,'2027-04-18');
assert.throws(()=>createDailyTickPersistenceExecutionAuthorization({package:executionPackage,approved:false}),e=>e.code==='DAILY_TICK_PERSISTENCE_EXECUTION_NOT_APPROVED');
assert.throws(()=>assertDailyTickPersistenceExecutionAuthorized(executionPackage,{...executionAuthorization,package:{...executionPackage}}),e=>e.code==='DAILY_TICK_PERSISTENCE_EXECUTION_AUTHORIZATION_MISMATCH');
assert.throws(()=>createDailyTickPersistenceExecutionAuthorization({package:{...executionPackage,days:2},approved:true}),e=>e.code==='INVALID_DAILY_TICK_PERSISTENCE_EXECUTION_AUTHORIZATION');
console.log('Daily tick persistence execution authorization tests passed.');
