'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {sortCPUReviewFeed}=require('./hlm-cpu-review-sort');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const base=sortCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(base.total,3);
const reverse=sortCPUReviewFeed(state,'PIT',{selections,reviewSortDirection:'desc'});
assert.deepStrictEqual(reverse.rows.map(x=>x.id),base.rows.map(x=>x.id).reverse());
const title=sortCPUReviewFeed(state,'PIT',{selections,reviewSortBy:'title'});
assert.strictEqual(title.rows.length,3);
const section=sortCPUReviewFeed(state,'PIT',{selections,reviewSortBy:'section'});
assert.strictEqual(section.rows[0].section,'Needs attention');
assert.throws(()=>sortCPUReviewFeed(state,'PIT',{reviewSortBy:'invalid'}),RangeError);
assert.throws(()=>sortCPUReviewFeed(state,'PIT',{reviewSortDirection:'invalid'}),RangeError);
assert.strictEqual(Object.isFrozen(base.rows),true);
assert.strictEqual(base.executionEnabled,false);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 381-385 CPU review sort tests passed.');
