'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {navigateCPUReviewFeed}=require('./hlm-cpu-review-feed-navigation');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const first=navigateCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(first.total,3);
assert.strictEqual(first.selectionFound,true);
assert.strictEqual(first.previousId,null);
assert.strictEqual(first.detail.action.kind,'inspect-only');
assert.strictEqual(first.executionEnabled,false);
const second=navigateCPUReviewFeed(state,'PIT',{selections,selectedReviewId:first.nextId});
assert.strictEqual(second.previousId,first.selectedId);
assert.strictEqual(second.selectionFound,true);
const missing=navigateCPUReviewFeed(state,'PIT',{selections,selectedReviewId:'missing-id'});
assert.strictEqual(missing.selectionFound,false);
assert.strictEqual(missing.detail,null);
assert.throws(()=>navigateCPUReviewFeed(state,'PIT',{selectedReviewId:123}),TypeError);
const empty=navigateCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.total,0);
assert.strictEqual(empty.detail,null);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 361-365 CPU review feed navigation tests passed.');
