'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {searchCPUReviewFeed}=require('./hlm-cpu-review-search');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const all=searchCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(all.total,3);
assert.strictEqual(all.matched,3);
const urgent=searchCPUReviewFeed(state,'PIT',{selections,searchSection:'Needs attention'});
assert.strictEqual(urgent.matched,2);
const query=searchCPUReviewFeed(state,'PIT',{selections,searchQuery:'  BLOCKED  '});
assert.strictEqual(query.query,'blocked');
assert.strictEqual(query.matched,2);
assert.strictEqual(query.results.every(x=>x.actionKind==='inspect-only'),true);
assert.throws(()=>searchCPUReviewFeed(state,'PIT',{searchSection:'invalid'}),RangeError);
assert.throws(()=>searchCPUReviewFeed(state,'PIT',{searchQuery:2}),RangeError);
const empty=searchCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.noMatches,true);
assert.strictEqual(Object.isFrozen(all),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 366-370 CPU review search tests passed.');
