'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const {createNextGameGameStateCalendarActivationAuthorization,assertNextGameGameStateCalendarActivationAuthorized}=require('./hlm-calendar-next-game-gamestate-activation-authorization');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'}});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const advancementAuthorization=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization:advancementAuthorization});
const advancementVerification=verifyNextGameCalendarAdvancement({plan,authorization:advancementAuthorization,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advancementVerification});
const verification=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
const authorization=createNextGameGameStateCalendarActivationAuthorization({verification,approved:true});
assert.strictEqual(authorization.kind,'next-game-gamestate-calendar-activation-authorization');assert.strictEqual(authorization.version,1);
assert.strictEqual(authorization.approved,true);assert.strictEqual(authorization.verification,verification);
assert.strictEqual(authorization.targetGame,verification.targetGame);assert.strictEqual(authorization.targetGame.type,'game');
assert.strictEqual(authorization.fromDate,'2027-03-03');assert.strictEqual(authorization.toDate,'2027-03-05');
assert.strictEqual(Object.isFrozen(authorization),true);assert.strictEqual(assertNextGameGameStateCalendarActivationAuthorized(verification,authorization),true);
assert.throws(()=>createNextGameGameStateCalendarActivationAuthorization({verification,approved:false}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_NOT_AUTHORIZED');
assert.throws(()=>assertNextGameGameStateCalendarActivationAuthorized({...verification},authorization),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_NOT_AUTHORIZED');
assert.throws(()=>assertNextGameGameStateCalendarActivationAuthorized(verification,{...authorization,targetGame:{...authorization.targetGame}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_NOT_AUTHORIZED');
assert.throws(()=>createNextGameGameStateCalendarActivationAuthorization({verification:{...verification,targetGame:{...verification.targetGame,type:'news'}},approved:true}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_NOT_AUTHORIZED');
console.log('Next-game GameState calendar activation authorization tests passed.');
