'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createDailyTickPlan}=require('./hlm-daily-tick-plan');
const {createDailyTickAuthorization}=require('./hlm-daily-tick-authorization');
const {executeIsolatedDailyTickCalendar}=require('./hlm-daily-tick-calendar-execution');
const {verifyDailyTickCalendarExecution}=require('./hlm-daily-tick-calendar-verification');
const {createDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate');
const {verifyDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate-verification');
const {createDailyTickGameStateCalendarActivationAuthorization}=require('./hlm-daily-tick-gamestate-activation-authorization');
const {activateDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-activation');
const {verifyIsolatedDailyTickGameStateCalendarActivation}=require('./hlm-daily-tick-gamestate-activation-verification');

const sourceState=createGameStateEnvelope({meta:{currentDate:'2027-04-17',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:sourceState.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2026-10-06',endDate:'2027-04-17'},{phaseId:'playoffs',startDate:'2027-04-18',endDate:'2027-06-20'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-04-18',important:true}]});
const plan=createDailyTickPlan({calendar,timeline,eventIndex});
const tickAuthorization=createDailyTickAuthorization({plan,approved:true});
const calendarResult=executeIsolatedDailyTickCalendar({calendar,plan,authorization:tickAuthorization});
const calendarVerification=verifyDailyTickCalendarExecution({sourceCalendar:calendar,plan,authorization:tickAuthorization,result:calendarResult});
const candidate=createDailyTickGameStateCalendarCandidate({state:sourceState,verification:calendarVerification});
const candidateVerification=verifyDailyTickGameStateCalendarCandidate({sourceState,candidate});
const authorization=createDailyTickGameStateCalendarActivationAuthorization({verification:candidateVerification,approved:true});
const activation=activateDailyTickGameStateCalendarCandidate({verification:candidateVerification,authorization});
const activationVerification=verifyIsolatedDailyTickGameStateCalendarActivation({activation});
const {createDailyTickPersistenceReadiness}=require('./hlm-daily-tick-persistence-readiness');
const readiness=createDailyTickPersistenceReadiness({verification:activationVerification});
const {createDailyTickPersistenceAuthorization,assertDailyTickPersistenceAuthorized}=require('./hlm-daily-tick-persistence-authorization');
const persistenceAuthorization=createDailyTickPersistenceAuthorization({readiness,approved:true});
const {createDailyTickPersistenceExecutionPackage}=require('./hlm-daily-tick-persistence-execution-package');
const executionPackage=createDailyTickPersistenceExecutionPackage({readiness,authorization:persistenceAuthorization});
assert.strictEqual(executionPackage.kind,'daily-tick-persistence-execution-package');assert.strictEqual(executionPackage.version,1);
assert.strictEqual(executionPackage.packaged,true);assert.strictEqual(executionPackage.executable,false);assert.strictEqual(executionPackage.days,1);
assert.strictEqual(executionPackage.fromDate,'2027-04-17');assert.strictEqual(executionPackage.toDate,'2027-04-18');
assert.strictEqual(executionPackage.readiness,readiness);assert.strictEqual(executionPackage.authorization,persistenceAuthorization);assert.strictEqual(executionPackage.candidateState,readiness.candidateState);
assert.strictEqual(executionPackage.transaction.verifyAfterWrite,true);assert.strictEqual(executionPackage.transaction.rollbackOnFailure,true);assert.strictEqual(executionPackage.transaction.executionAuthorizationRequired,true);
assert.strictEqual(Object.isFrozen(executionPackage),true);assert.strictEqual(Object.isFrozen(executionPackage.transaction),true);
assert.strictEqual(sourceState.meta.currentDate,'2027-04-17');assert.strictEqual(executionPackage.candidateState.meta.currentDate,'2027-04-18');
assert.throws(()=>createDailyTickPersistenceExecutionPackage({readiness,authorization:{...persistenceAuthorization,readiness:{...readiness}}}),e=>e.code==='INVALID_DAILY_TICK_PERSISTENCE_EXECUTION_PACKAGE');
assert.throws(()=>createDailyTickPersistenceExecutionPackage({readiness:{...readiness,days:2},authorization:persistenceAuthorization}),e=>e.code==='INVALID_DAILY_TICK_PERSISTENCE_EXECUTION_PACKAGE');
console.log('Daily tick persistence execution package tests passed.');
