'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {queryCPUReviewFeed}=require('./hlm-cpu-review-query');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const first=queryCPUReviewFeed(state,'PIT',{selections,reviewPageSize:2});
assert.strictEqual(first.total,3);
assert.strictEqual(first.rows.length,2);
assert.strictEqual(first.hasNext,true);
const filtered=queryCPUReviewFeed(state,'PIT',{selections,reviewStatus:'blocked',reviewSortBy:'title',reviewPageSize:1,reviewPage:2});
assert.strictEqual(filtered.total,2);
assert.strictEqual(filtered.rows.length,1);
assert.strictEqual(filtered.hasPrevious,true);
assert.strictEqual(filtered.hasNext,false);
assert.strictEqual(filtered.executionEnabled,false);
assert.throws(()=>queryCPUReviewFeed(state,'PIT',{reviewPage:0}),RangeError);
assert.throws(()=>queryCPUReviewFeed(state,'PIT',{reviewPageSize:101}),RangeError);
const empty=queryCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.totalPages,0);
assert.strictEqual(empty.empty,true);
assert.strictEqual(Object.isFrozen(first.rows),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 386-390 CPU review query tests passed.');
