'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {summarizeCPUReviewFeed}=require('./hlm-cpu-review-summary');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const summary=summarizeCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(summary.totalMatches,3);
assert.strictEqual(summary.counts.urgent,2);
assert.strictEqual(summary.counts.blocked,2);
assert.strictEqual(summary.counts.awaitingReview,1);
assert.strictEqual(summary.partial,false);
assert.strictEqual(summary.executionEnabled,false);
assert.ok(summary.nextReviewId);
const empty=summarizeCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.empty,true);
assert.strictEqual(empty.nextReviewId,null);
assert.strictEqual(Object.isFrozen(summary.counts),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 396-400 CPU review summary tests passed.');
