'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {presentCPUReviewFeed}=require('./hlm-cpu-review-feed-presentation');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const view=presentCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(view.total,3);
assert.strictEqual(view.sections.length,2);
assert.strictEqual(view.sections[0].rows.length,2);
assert.strictEqual(view.sections[1].rows.length,1);
assert.strictEqual(view.rows.every(x=>x.action.kind==='inspect-only'&&x.executionEnabled===false),true);
assert.strictEqual(view.executionEnabled,false);
assert.strictEqual(Object.isFrozen(view),true);
const empty=presentCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.total,0);
assert.strictEqual(typeof empty.emptyMessage,'string');
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 356-360 CPU review feed presentation tests passed.');
