'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {summarizeCPUReviewQueue}=require('./hlm-cpu-review-queue-summary');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const result=summarizeCPUReviewQueue(state,'PIT',{selections:[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}]});
assert.strictEqual(result.summary.total,3);
assert.strictEqual(result.summary.blocked,2);
assert.strictEqual(result.summary.awaitingExecution,1);
assert.strictEqual(result.summary.nextReviewId,result.prioritization.items[0].id);
assert.strictEqual(result.summary.nextReviewStatus,'blocked');
assert.strictEqual(result.summary.executedCount,0);
assert.strictEqual(result.summary.executionEnabled,false);
assert.strictEqual(result.summary.requiresHumanReview,true);
const empty=summarizeCPUReviewQueue(state,'PIT');
assert.strictEqual(empty.summary.total,0);
assert.strictEqual(empty.summary.nextReviewId,null);
assert.strictEqual(empty.summary.requiresHumanReview,false);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 CPU review queue summary tests passed.');
