'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const {createNextGameGameStateCalendarActivationAuthorization}=require('./hlm-calendar-next-game-gamestate-activation-authorization');
const {activateNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-activation');
const {verifyIsolatedNextGameGameStateCalendarActivation}=require('./hlm-calendar-next-game-gamestate-activation-verification');
const {createNextGameCalendarPersistenceReadiness}=require('./hlm-calendar-next-game-persistence-readiness');
const {createNextGameCalendarPersistenceAuthorization,assertNextGameCalendarPersistenceAuthorized}=require('./hlm-calendar-next-game-persistence-authorization');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'}});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const advanceAuth=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization:advanceAuth});
const advanceVerify=verifyNextGameCalendarAdvancement({plan,authorization:advanceAuth,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advanceVerify});
const candidateVerify=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
const activationAuth=createNextGameGameStateCalendarActivationAuthorization({verification:candidateVerify,approved:true});
const activation=activateNextGameGameStateCalendarCandidate({verification:candidateVerify,authorization:activationAuth});
const activationVerify=verifyIsolatedNextGameGameStateCalendarActivation({activation});
const readiness=createNextGameCalendarPersistenceReadiness({verification:activationVerify});
const authorization=createNextGameCalendarPersistenceAuthorization({readiness,approved:true});
assert.strictEqual(authorization.kind,'next-game-calendar-persistence-authorization');assert.strictEqual(authorization.version,1);
assert.strictEqual(authorization.approved,true);assert.strictEqual(authorization.readiness,readiness);
assert.strictEqual(authorization.targetGame,readiness.targetGame);assert.strictEqual(authorization.targetGame.type,'game');
assert.strictEqual(authorization.candidateState,readiness.candidateState);assert.strictEqual(authorization.fromDate,'2027-03-03');
assert.strictEqual(authorization.toDate,'2027-03-05');assert.strictEqual(Object.isFrozen(authorization),true);
assert.strictEqual(assertNextGameCalendarPersistenceAuthorized(readiness,authorization),true);
assert.throws(()=>createNextGameCalendarPersistenceAuthorization({readiness,approved:false}),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_NOT_APPROVED');
assert.throws(()=>assertNextGameCalendarPersistenceAuthorized({...readiness},authorization),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_AUTHORIZATION_MISMATCH');
assert.throws(()=>assertNextGameCalendarPersistenceAuthorized(readiness,{...authorization,targetGame:{...authorization.targetGame}}),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_AUTHORIZATION_MISMATCH');
console.log('Next-game calendar persistence authorization tests passed.');
