'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUReviewFeed}=require('./hlm-cpu-review-feed');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const feed=createCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(feed.total,3);
assert.strictEqual(feed.entries[0].urgency,'urgent');
assert.strictEqual(feed.entries[1].urgency,'urgent');
assert.strictEqual(feed.entries[2].urgency,'standard');
assert.strictEqual(feed.entries.every(x=>x.humanReviewRequired&&!x.executionAuthorized),true);
assert.strictEqual(feed.executionEnabled,false);
assert.strictEqual(Object.isFrozen(feed.entries),true);
assert.strictEqual(JSON.parse(JSON.stringify(feed)).total,3);
const empty=createCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.total,0);
assert.strictEqual(empty.nextReviewId,null);
assert.strictEqual(typeof empty.emptyMessage,'string');
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 351-355 CPU review feed tests passed.');
