'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUReviewBriefing}=require('./hlm-cpu-review-briefing');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const result=createCPUReviewBriefing(state,'PIT',{selections});
assert.deepStrictEqual(result.summary,{total:3,visible:3,blocked:2,pending:1,requiresHumanReview:true});
assert.strictEqual(result.urgent.length,2);
assert.strictEqual(result.standard.length,1);
assert.strictEqual(result.nextSteps.reduce((n,x)=>n+x.count,0),3);
assert.strictEqual(result.executionEnabled,false);
assert.strictEqual(Object.isFrozen(result),true);
assert.strictEqual(Object.isFrozen(result.summary),true);
const filtered=createCPUReviewBriefing(state,'PIT',{selections,triageStatusFilter:'blocked'});
assert.strictEqual(filtered.urgent.length,2);
assert.strictEqual(filtered.standard.length,0);
const empty=createCPUReviewBriefing(state,'PIT');
assert.strictEqual(empty.summary.total,0);
assert.strictEqual(empty.nextReviewId,null);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 341-345 CPU review briefing tests passed.');
