'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {auditCPUReviewQueue}=require('./hlm-cpu-review-audit');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const audit=auditCPUReviewQueue(state,'PIT',{selections});
assert.strictEqual(audit.valid,true);
assert.deepStrictEqual(audit.problems,[]);
assert.deepStrictEqual(audit.counts,{total:3,unique:3,groupTotal:3,actionTotal:3});
assert.strictEqual(audit.requiresHumanReview,true);
assert.strictEqual(audit.executionEnabled,false);
assert.strictEqual(audit.report.executedCount,0);
assert.strictEqual(Object.isFrozen(audit),true);
const empty=auditCPUReviewQueue(state,'PIT');
assert.strictEqual(empty.valid,true);
assert.strictEqual(empty.counts.total,0);
assert.strictEqual(empty.requiresHumanReview,false);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 326-330 CPU review audit tests passed.');
