'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createDailyTickPlan}=require('./hlm-daily-tick-plan');
const {createDailyTickAuthorization}=require('./hlm-daily-tick-authorization');
const {executeIsolatedDailyTickCalendar}=require('./hlm-daily-tick-calendar-execution');
const {verifyDailyTickCalendarExecution}=require('./hlm-daily-tick-calendar-verification');
const {createDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate');
const {verifyDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate-verification');
const {createDailyTickGameStateCalendarActivationAuthorization}=require('./hlm-daily-tick-gamestate-activation-authorization');
const {activateDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-activation');

const sourceState=createGameStateEnvelope({meta:{currentDate:'2027-04-17',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:sourceState.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2026-10-06',endDate:'2027-04-17'},{phaseId:'playoffs',startDate:'2027-04-18',endDate:'2027-06-20'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-04-18',important:true}]});
const plan=createDailyTickPlan({calendar,timeline,eventIndex});
const tickAuthorization=createDailyTickAuthorization({plan,approved:true});
const calendarResult=executeIsolatedDailyTickCalendar({calendar,plan,authorization:tickAuthorization});
const calendarVerification=verifyDailyTickCalendarExecution({sourceCalendar:calendar,plan,authorization:tickAuthorization,result:calendarResult});
const candidate=createDailyTickGameStateCalendarCandidate({state:sourceState,verification:calendarVerification});
const verification=verifyDailyTickGameStateCalendarCandidate({sourceState,candidate});
const authorization=createDailyTickGameStateCalendarActivationAuthorization({verification,approved:true});
const activation=activateDailyTickGameStateCalendarCandidate({verification,authorization});
assert.strictEqual(activation.kind,'isolated-daily-tick-gamestate-calendar-activation');assert.strictEqual(activation.version,1);
assert.strictEqual(activation.activated,true);assert.strictEqual(activation.fromDate,'2027-04-17');assert.strictEqual(activation.toDate,'2027-04-18');assert.strictEqual(activation.days,1);
assert.strictEqual(activation.verification,verification);assert.strictEqual(activation.authorization,authorization);
assert.strictEqual(activation.state,candidate.state);assert.strictEqual(activation.state.meta.currentDate,'2027-04-18');
assert.strictEqual(sourceState.meta.currentDate,'2027-04-17');assert.deepStrictEqual(activation.state.universe.players,sourceState.universe.players);
assert.strictEqual(activation.eventsProcessed,false);assert.strictEqual(activation.gameSimulationPerformed,false);
assert.strictEqual(activation.universeSystemsProcessed,false);assert.strictEqual(activation.persistencePerformed,false);
assert.strictEqual(Object.isFrozen(activation),true);
assert.throws(()=>activateDailyTickGameStateCalendarCandidate({verification,authorization:{...authorization,verification:{...verification}}}),e=>e.code==='DAILY_TICK_GAMESTATE_CALENDAR_ACTIVATION_FAILED');
assert.throws(()=>activateDailyTickGameStateCalendarCandidate({verification:{...verification,candidate:{...candidate,eventsProcessed:true}},authorization}),e=>e.code==='DAILY_TICK_GAMESTATE_CALENDAR_ACTIVATION_FAILED');
console.log('Isolated daily tick GameState calendar activation tests passed.');
