'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createDailyTickPlan}=require('./hlm-daily-tick-plan');
const {createDailyTickAuthorization}=require('./hlm-daily-tick-authorization');
const {executeIsolatedDailyTickCalendar}=require('./hlm-daily-tick-calendar-execution');
const {verifyDailyTickCalendarExecution}=require('./hlm-daily-tick-calendar-verification');
const {createDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate');
const {verifyDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-candidate-verification');
const {createDailyTickGameStateCalendarActivationAuthorization}=require('./hlm-daily-tick-gamestate-activation-authorization');
const {activateDailyTickGameStateCalendarCandidate}=require('./hlm-daily-tick-gamestate-activation');
const {verifyIsolatedDailyTickGameStateCalendarActivation}=require('./hlm-daily-tick-gamestate-activation-verification');

const sourceState=createGameStateEnvelope({meta:{currentDate:'2027-04-17',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:sourceState.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2026-10-06',endDate:'2027-04-17'},{phaseId:'playoffs',startDate:'2027-04-18',endDate:'2027-06-20'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-04-18',important:true}]});
const plan=createDailyTickPlan({calendar,timeline,eventIndex});
const tickAuthorization=createDailyTickAuthorization({plan,approved:true});
const calendarResult=executeIsolatedDailyTickCalendar({calendar,plan,authorization:tickAuthorization});
const calendarVerification=verifyDailyTickCalendarExecution({sourceCalendar:calendar,plan,authorization:tickAuthorization,result:calendarResult});
const candidate=createDailyTickGameStateCalendarCandidate({state:sourceState,verification:calendarVerification});
const candidateVerification=verifyDailyTickGameStateCalendarCandidate({sourceState,candidate});
const authorization=createDailyTickGameStateCalendarActivationAuthorization({verification:candidateVerification,approved:true});
const activation=activateDailyTickGameStateCalendarCandidate({verification:candidateVerification,authorization});
const activationVerification=verifyIsolatedDailyTickGameStateCalendarActivation({activation});
const {createDailyTickPersistenceReadiness}=require('./hlm-daily-tick-persistence-readiness');
const readiness=createDailyTickPersistenceReadiness({verification:activationVerification});
assert.strictEqual(readiness.kind,'daily-tick-persistence-readiness');assert.strictEqual(readiness.version,1);assert.strictEqual(readiness.ready,true);
assert.strictEqual(readiness.fromDate,'2027-04-17');assert.strictEqual(readiness.toDate,'2027-04-18');assert.strictEqual(readiness.days,1);
assert.strictEqual(readiness.verification,activationVerification);assert.strictEqual(readiness.candidateState,activation.state);
assert.strictEqual(readiness.candidateState.meta.currentDate,'2027-04-18');assert.strictEqual(sourceState.meta.currentDate,'2027-04-17');
assert.strictEqual(readiness.requirements.explicitPersistenceAuthorizationRequired,true);assert.strictEqual(readiness.requirements.verifyAfterWriteRequired,true);assert.strictEqual(readiness.requirements.rollbackOnFailureRequired,true);
assert.strictEqual(Object.isFrozen(readiness),true);assert.strictEqual(Object.isFrozen(readiness.requirements),true);
assert.throws(()=>createDailyTickPersistenceReadiness({verification:{...activationVerification,persistencePerformed:true}}),e=>e.code==='DAILY_TICK_PERSISTENCE_NOT_READY');
assert.throws(()=>createDailyTickPersistenceReadiness({verification:{...activationVerification,days:2}}),e=>e.code==='DAILY_TICK_PERSISTENCE_NOT_READY');
assert.throws(()=>createDailyTickPersistenceReadiness({verification:{...activationVerification,activation:{...activation,persistencePerformed:true}}}),e=>e.code==='DAILY_TICK_PERSISTENCE_NOT_READY');
console.log('Daily tick persistence readiness tests passed.');
