'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {buildCPUReviewDashboard}=require('./hlm-cpu-review-dashboard');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const result=buildCPUReviewDashboard(state,'PIT',{selections});
assert.strictEqual(result.counters.total,3);
assert.strictEqual(result.counters.urgent,2);
assert.strictEqual(result.counters.standard,1);
assert.strictEqual(result.lanes.length,2);
assert.strictEqual(result.lanes[0].count,2);
assert.strictEqual(result.actionBreakdown.reduce((n,x)=>n+x.count,0),3);
assert.strictEqual(result.nextDecision.requiresHumanReview,true);
assert.strictEqual(result.executionEnabled,false);
assert.strictEqual(Object.isFrozen(result),true);
const empty=buildCPUReviewDashboard(state,'PIT');
assert.strictEqual(empty.counters.total,0);
assert.strictEqual(empty.nextDecision,null);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 346-350 CPU review dashboard tests passed.');
