'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUActionAuthorizationVerification,verifyCPUActionAuthorization}=require('./hlm-cpu-action-authorization-verification');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const options={prioritization,priorityId:'first'};
const denied=createCPUActionAuthorizationVerification(state,'PIT',options);
assert.strictEqual(denied.validation.valid,false);
assert(denied.verification.reasons.includes('human-authorization-missing'));
const approved=createCPUActionAuthorizationVerification(state,'PIT',{...options,authorized:true});
assert.strictEqual(approved.validation.valid,true);
assert.strictEqual(approved.verification.verified,true);
assert.strictEqual(approved.decisionStage.actPerformed,false);
assert.strictEqual(approved.persistencePerformed,false);
assert.strictEqual(JSON.stringify(state),before);
const tampered={...approved.authorizationPackage,authority:{cpuDecisionExecutionEnabled:true}};
assert.strictEqual(verifyCPUActionAuthorization(tampered).verified,false);
assert(verifyCPUActionAuthorization(tampered).reasons.includes('execution-boundary-violated'));
const missing=createCPUActionAuthorizationVerification(state,'PIT',{...options,priorityId:'missing',authorized:true});
assert.strictEqual(missing.validation.valid,false);
assert.throws(()=>createCPUActionAuthorizationVerification(state,'MISSING',{...options,authorized:true}),/Team not found/);
console.log('Phase 9 CPU action authorization verification tests passed.');
