'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {paginateCPUReviewFeed}=require('./hlm-cpu-review-pagination');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const first=paginateCPUReviewFeed(state,'PIT',{selections,reviewPageSize:2});
assert.strictEqual(first.total,3);
assert.strictEqual(first.totalPages,2);
assert.strictEqual(first.rows.length,2);
assert.strictEqual(first.hasNext,true);
assert.strictEqual(first.hasPrevious,false);
const second=paginateCPUReviewFeed(state,'PIT',{selections,reviewPage:2,reviewPageSize:2});
assert.strictEqual(second.rows.length,1);
assert.strictEqual(second.hasPrevious,true);
assert.strictEqual(second.hasNext,false);
const beyond=paginateCPUReviewFeed(state,'PIT',{selections,reviewPage:3,reviewPageSize:2});
assert.strictEqual(beyond.outOfRange,true);
assert.strictEqual(beyond.rows.length,0);
assert.throws(()=>paginateCPUReviewFeed(state,'PIT',{reviewPage:0}),RangeError);
assert.throws(()=>paginateCPUReviewFeed(state,'PIT',{reviewPageSize:101}),RangeError);
const empty=paginateCPUReviewFeed(state,'PIT');
assert.strictEqual(empty.totalPages,0);
assert.strictEqual(empty.empty,true);
assert.strictEqual(Object.isFrozen(first),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 371-375 CPU review pagination tests passed.');
