'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {triageCPUReviewQueue}=require('./hlm-cpu-review-triage');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const all=triageCPUReviewQueue(state,'PIT',{selections});
assert.strictEqual(all.total,3);
assert.strictEqual(all.visible,3);
assert.strictEqual(all.blocked,2);
assert.strictEqual(all.pending,1);
assert.strictEqual(all.entries[0].priority,'urgent-review');
assert.strictEqual(all.nextReviewReason,'resolve-blocker');
assert.strictEqual(all.executionEnabled,false);
assert.strictEqual(Object.isFrozen(all.entries),true);
const filtered=triageCPUReviewQueue(state,'PIT',{selections,triageStatusFilter:'awaiting-execution'});
assert.strictEqual(filtered.visible,1);
assert.strictEqual(filtered.entries[0].priority,'standard-review');
assert.strictEqual(filtered.nextReviewReason,'human-review-required');
assert.throws(()=>triageCPUReviewQueue(state,'PIT',{triageStatusFilter:'invalid'}),RangeError);
const empty=triageCPUReviewQueue(state,'PIT');
assert.strictEqual(empty.total,0);
assert.strictEqual(empty.nextReviewId,null);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 336-340 CPU review triage tests passed.');
