'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {filterCPUReviewFeed}=require('./hlm-cpu-review-filters');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const selections=[{prioritization,priorityId:'first',authorized:true,execute:true},{prioritization,priorityId:'first',execute:true},{prioritization,priorityId:'missing',authorized:true,execute:true}];
const all=filterCPUReviewFeed(state,'PIT',{selections});
assert.strictEqual(all.matched,3);
const blocked=filterCPUReviewFeed(state,'PIT',{selections,reviewStatus:'blocked'});
assert.strictEqual(blocked.matched,2);
const urgent=filterCPUReviewFeed(state,'PIT',{selections,reviewUrgency:'urgent'});
assert.strictEqual(urgent.matched,2);
const combined=filterCPUReviewFeed(state,'PIT',{selections,reviewUrgency:'urgent',reviewStatus:'blocked'});
assert.strictEqual(combined.matched,2);
assert.strictEqual(combined.filtersActive,true);
assert.strictEqual(combined.executionEnabled,false);
assert.throws(()=>filterCPUReviewFeed(state,'PIT',{reviewStatus:'invalid'}),RangeError);
assert.throws(()=>filterCPUReviewFeed(state,'PIT',{reviewUrgency:'invalid'}),RangeError);
assert.strictEqual(Object.isFrozen(all),true);
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 Missions 376-380 CPU review filters tests passed.');
