'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUDecisionCycleSummary}=require('./hlm-cpu-decision-cycle-summary');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const r=createCPUDecisionCycleSummary(state,'PIT',{prioritization,priorityId:'first',authorized:true,execute:true});
assert.strictEqual(r.summary.priorityId,'first');
assert.strictEqual(r.summary.optionId,'trade-option');
assert.strictEqual(r.summary.humanAuthorized,true);
assert.strictEqual(r.summary.verificationPassed,true);
assert.strictEqual(r.summary.outcomeStatus,'awaiting-execution');
assert.strictEqual(r.summary.actionPerformed,false);
assert.strictEqual(r.summary.cycleCompleted,false);
assert.strictEqual(r.persistencePerformed,false);
assert.strictEqual(JSON.stringify(state),before);
const blocked=createCPUDecisionCycleSummary(state,'PIT',{prioritization,priorityId:'first',execute:true});
assert.strictEqual(blocked.summary.verificationPassed,false);
assert.strictEqual(blocked.summary.outcomeStatus,'blocked');
console.log('Phase 9 CPU decision cycle summary tests passed.');
