'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const {createNextGameGameStateCalendarActivationAuthorization}=require('./hlm-calendar-next-game-gamestate-activation-authorization');
const {activateNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-activation');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'},players:[{id:'p1',name:'Player One'}]});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const advancementAuthorization=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization:advancementAuthorization});
const advancementVerification=verifyNextGameCalendarAdvancement({plan,authorization:advancementAuthorization,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advancementVerification});
const verification=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
const authorization=createNextGameGameStateCalendarActivationAuthorization({verification,approved:true});
const activation=activateNextGameGameStateCalendarCandidate({verification,authorization});
assert.strictEqual(activation.kind,'isolated-next-game-gamestate-calendar-activation');assert.strictEqual(activation.version,1);
assert.strictEqual(activation.activated,true);assert.strictEqual(activation.fromDate,'2027-03-03');assert.strictEqual(activation.toDate,'2027-03-05');
assert.strictEqual(activation.targetGame,verification.targetGame);assert.strictEqual(activation.targetGame.type,'game');
assert.strictEqual(activation.verification,verification);assert.strictEqual(activation.authorization,authorization);
assert.strictEqual(activation.state,candidate.state);assert.strictEqual(activation.state.meta.currentDate,'2027-03-05');
assert.strictEqual(activation.state.meta.controlledTeamId,'PIT');assert.strictEqual(state.meta.currentDate,'2027-03-03');
assert.strictEqual(Object.isFrozen(activation),true);
assert.throws(()=>activateNextGameGameStateCalendarCandidate({verification:{...verification},authorization}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_FAILED');
assert.throws(()=>activateNextGameGameStateCalendarCandidate({verification,authorization:{...authorization,targetGame:{...authorization.targetGame}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_FAILED');
console.log('Isolated next-game GameState calendar activation tests passed.');
