'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const {createNextGameGameStateCalendarActivationAuthorization}=require('./hlm-calendar-next-game-gamestate-activation-authorization');
const {activateNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-activation');
const {verifyIsolatedNextGameGameStateCalendarActivation}=require('./hlm-calendar-next-game-gamestate-activation-verification');
const {createNextGameCalendarPersistenceReadiness}=require('./hlm-calendar-next-game-persistence-readiness');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'}});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const advanceAuth=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization:advanceAuth});
const advanceVerify=verifyNextGameCalendarAdvancement({plan,authorization:advanceAuth,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advanceVerify});
const candidateVerify=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
const activationAuth=createNextGameGameStateCalendarActivationAuthorization({verification:candidateVerify,approved:true});
const activation=activateNextGameGameStateCalendarCandidate({verification:candidateVerify,authorization:activationAuth});
const activationVerify=verifyIsolatedNextGameGameStateCalendarActivation({activation});
const readiness=createNextGameCalendarPersistenceReadiness({verification:activationVerify});
assert.strictEqual(readiness.kind,'next-game-calendar-persistence-readiness');assert.strictEqual(readiness.version,1);assert.strictEqual(readiness.ready,true);
assert.strictEqual(readiness.fromDate,'2027-03-03');assert.strictEqual(readiness.toDate,'2027-03-05');
assert.strictEqual(readiness.targetGame,activationVerify.targetGame);assert.strictEqual(readiness.targetGame.type,'game');
assert.strictEqual(readiness.verification,activationVerify);assert.strictEqual(readiness.candidateState,activation.state);
assert.strictEqual(readiness.requirements.explicitPersistenceAuthorizationRequired,true);
assert.strictEqual(readiness.requirements.verifyAfterWriteRequired,true);assert.strictEqual(readiness.requirements.rollbackOnFailureRequired,true);
assert.strictEqual(Object.isFrozen(readiness),true);assert.strictEqual(Object.isFrozen(readiness.requirements),true);
assert.throws(()=>createNextGameCalendarPersistenceReadiness({verification:{...activationVerify,verified:false}}),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_NOT_READY');
assert.throws(()=>createNextGameCalendarPersistenceReadiness({verification:{...activationVerify,targetGame:{...activationVerify.targetGame}}}),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_NOT_READY');
assert.throws(()=>createNextGameCalendarPersistenceReadiness({verification:{...activationVerify,state}}),e=>e.code==='NEXT_GAME_CALENDAR_PERSISTENCE_NOT_READY');
console.log('Next-game calendar persistence readiness tests passed.');
