'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createCPUDecisionCycleDiagnostics}=require('./hlm-cpu-decision-cycle-diagnostics');
const state=createGameStateEnvelope({teams:[{id:'PIT',name:'Pittsburgh'}],players:[],contracts:[],draftPicks:[]});
const before=JSON.stringify(state);
const prioritization={evaluation:{identification:{problems:[{id:'cap-pressure',category:'cap',severity:'high'}]},options:[{id:'trade-option',problemId:'cap-pressure',type:'trades'}]},priorities:[{id:'first',optionId:'trade-option',tier:'high',order:1}]};
const ready=createCPUDecisionCycleDiagnostics(state,'PIT',{prioritization,priorityId:'first',authorized:true,execute:true});
assert.strictEqual(ready.diagnostics.status,'awaiting-execution');
assert.strictEqual(ready.diagnostics.reason,'action-not-executed');
assert.strictEqual(ready.diagnostics.remediationRequired,false);
assert.strictEqual(ready.diagnostics.executorEnabled,false);
const denied=createCPUDecisionCycleDiagnostics(state,'PIT',{prioritization,priorityId:'first',execute:true});
assert.strictEqual(denied.diagnostics.status,'blocked');
assert.strictEqual(denied.diagnostics.reason,'human-authorization-required');
assert.strictEqual(denied.diagnostics.remediationRequired,true);
const invalid=createCPUDecisionCycleDiagnostics(state,'PIT',{prioritization,priorityId:'missing',authorized:true,execute:true});
assert.strictEqual(invalid.diagnostics.reason,'invalid-or-missing-action-candidate');
assert.strictEqual(JSON.stringify(state),before);
console.log('Phase 9 CPU decision cycle diagnostics tests passed.');
