'use strict';
const assert=require('assert');
const {createGameStateEnvelope}=require('./hlm-game-state');
const {createMasterCalendar}=require('./hlm-master-calendar');
const {createSeasonPhaseTimeline}=require('./hlm-season-phase-timeline');
const {createCalendarEventIndex}=require('./hlm-calendar-event');
const {createNextGameCalendarAdvancementPlan}=require('./hlm-calendar-next-game-advancement-plan');
const {createNextGameCalendarAdvancementAuthorization}=require('./hlm-calendar-next-game-advancement-authorization');
const {executeIsolatedNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-execution');
const {verifyNextGameCalendarAdvancement}=require('./hlm-calendar-next-game-advancement-verification');
const {createNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate');
const {verifyNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-candidate-verification');
const {createNextGameGameStateCalendarActivationAuthorization}=require('./hlm-calendar-next-game-gamestate-activation-authorization');
const {activateNextGameGameStateCalendarCandidate}=require('./hlm-calendar-next-game-gamestate-activation');
const {verifyIsolatedNextGameGameStateCalendarActivation}=require('./hlm-calendar-next-game-gamestate-activation-verification');
const state=createGameStateEnvelope({meta:{currentDate:'2027-03-03',controlledTeamId:'PIT'}});
const calendar=createMasterCalendar({currentDate:state.meta.currentDate});
const timeline=createSeasonPhaseTimeline({windows:[{phaseId:'regular-season',startDate:'2027-03-01',endDate:'2027-03-10'}]});
const eventIndex=createCalendarEventIndex({events:[{id:'game-1',type:'game',date:'2027-03-05',important:true}]});
const plan=createNextGameCalendarAdvancementPlan({calendar,timeline,eventIndex});
const advanceAuth=createNextGameCalendarAdvancementAuthorization({plan,approved:true});
const result=executeIsolatedNextGameCalendarAdvancement({calendar,plan,authorization:advanceAuth});
const advanceVerify=verifyNextGameCalendarAdvancement({plan,authorization:advanceAuth,result});
const candidate=createNextGameGameStateCalendarCandidate({state,verification:advanceVerify});
const candidateVerify=verifyNextGameGameStateCalendarCandidate({sourceState:state,candidate});
const activationAuth=createNextGameGameStateCalendarActivationAuthorization({verification:candidateVerify,approved:true});
const activation=activateNextGameGameStateCalendarCandidate({verification:candidateVerify,authorization:activationAuth});
const verification=verifyIsolatedNextGameGameStateCalendarActivation({activation});
assert.strictEqual(verification.kind,'isolated-next-game-gamestate-calendar-activation-verification');assert.strictEqual(verification.version,1);
assert.strictEqual(verification.verified,true);assert.strictEqual(verification.targetGameMatched,true);
assert.strictEqual(verification.candidateIdentityPreserved,true);assert.strictEqual(verification.authorizationLineageVerified,true);
assert.strictEqual(verification.activation,activation);assert.strictEqual(verification.state,activation.state);
assert.strictEqual(verification.targetGame,activation.targetGame);assert.strictEqual(verification.targetGame.type,'game');
assert.strictEqual(verification.toDate,'2027-03-05');assert.strictEqual(state.meta.currentDate,'2027-03-03');
assert.strictEqual(Object.isFrozen(verification),true);
assert.throws(()=>verifyIsolatedNextGameGameStateCalendarActivation({activation:{...activation,targetGame:{...activation.targetGame}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
assert.throws(()=>verifyIsolatedNextGameGameStateCalendarActivation({activation:{...activation,authorization:{...activation.authorization,verification:{...activation.verification}}}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
assert.throws(()=>verifyIsolatedNextGameGameStateCalendarActivation({activation:{...activation,state}}),e=>e.code==='NEXT_GAME_GAMESTATE_CALENDAR_ACTIVATION_VERIFICATION_FAILED');
console.log('Isolated next-game GameState calendar activation verification tests passed.');
